// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxjddodfdrqnwozdrike.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4amRkb2RmZHJxbndvemRyaWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTgxODcsImV4cCI6MjA3MDIzNDE4N30.hyKpOcdCZh4TZwwYSIrDEV_yygsulkgsoA1h2L1pMXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});